name: Build and test minimial_f2py_package on github actions

on: push

jobs:
  build-and-test:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
        os: ["ubuntu-latest", ]
        include:
          - os: ubuntu-latest
            environment-file: ci/requirements-linux.yml
          - os: macos-latest
            environment-file: ci/requirements-macos.yml

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test_env
          python-version: ${{ matrix.python-version }}
          environment-file: ${{ matrix.environment-file }}
          miniconda-version: latest
      - name: Build and install
        run: |
          echo "Where are we?"
          pwd
          python -m pip install --verbose --no-deps --editable .
      - name: Check out conda env details
        run: |
          conda info
          conda list
      - name: Import minimalf2py
        run: |
          python -c "import minimalf2py"
      - name: Run tests
        run: |
          pytest --verbose --pyargs minimalf2py.tests
