name: Build and test minimial_f2py_package for windows on github actions

on: push

jobs:
  build-and-test:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: powershell
    strategy:
      fail-fast: false
      matrix:
        #python-version: ["3.7", "3.8"]
        python-version: ["3.8"]
        os: ["windows-latest"]
        include:
          - os: windows-latest
            environment-file: ci/requirements-windows.yml

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test_env
          python-version: ${{ matrix.python-version }}
          environment-file: ${{ matrix.environment-file }}
          miniforge-version: latest
          auto-update-conda: false
          use-only-tar-bz2: true
      - name: Build and install
        run: |
          python -m pip install . --no-index --no-deps -vv
          conda info
          conda list
      - name: Check out conda env details
        shell: powershell
        run: |
          conda info
          conda list
      - name: Import minimal_f2py_package
        shell: powershell
        run: |
          python -c "import minimal_f2py_package"
      - name: Run tests
        run: |
          pytest -v --pyargs minimal_f2py_package.tests
